FROM continuumio/miniconda3:22.11.1
LABEL author="Alberto Polini"


RUN apt-get update && \
    apt-get install -yq --no-install-recommends \
    curl \ 
    wget \
    git \
    gnupg \
    jq 
    

# Nodejs required to install jupyter-lab extension
    
RUN curl -fsSL https://deb.nodesource.com/setup_current.x | bash - && \
    apt-get install -y nodejs \
    build-essential && \
    node --version && \ 
    npm --version

RUN conda install \
    "jupyterlab>=3" "ipywidgets>=7.6" 



COPY requirements.txt .

# Installazione dei pacchetti Python
RUN pip install -r requirements.txt
RUN pip install torch torchvision torchaudio


WORKDIR /home


EXPOSE 8888

ARG token_name=token
ENV JUPYTER_TOKEN=$token_name

# Aggiunte per controllare che il token sia preso correttamente
RUN echo $token_name 
RUN echo $JUPYTER_TOKEN 

CMD ["jupyter-lab","--ip=0.0.0.0","--no-browser","--allow-root"]

